package pojo;
// Generated Oct 4, 2018 12:45:40 PM by Hibernate Tools 4.3.1


import dao.RecipeDAO;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.servlet.http.Part;

/**
 * Projekmyspek generated by hbm2java
 */
@Entity
@Table(name="projekmyspek"
    ,catalog="dbimg"
)
@ManagedBean
@SessionScoped
public class Projekmyspek  implements java.io.Serializable {


     private Integer id;
     private String path;
     private String network;
     private String launch;
     private String display;
     private String platform;
     private String memory;
     private String maincamera;
     private String selfiecamera;
     private String sound;
     private String comms;
     private String features;
     private String battery;
     private String misc;
     private String username;
     private String msg;     
     private Part image;
     private List<Projekmyspek> listspek;
     private int selectedspek;

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    public Part getImage() {
        return image;
    }

    public void setImage(Part image) {
        this.image = image;
    }


    public Projekmyspek() {
    }

    public Projekmyspek(String path, String network, String launch, String display, String platform, String memory, String maincamera, String selfiecamera, String sound, String comms, String features, String battery, String misc, String username) {
       this.path = path;
       this.network = network;
       this.launch = launch;
       this.display = display;
       this.platform = platform;
       this.memory = memory;
       this.maincamera = maincamera;
       this.selfiecamera = selfiecamera;
       this.sound = sound;
       this.comms = comms;
       this.features = features;
       this.battery = battery;
       this.misc = misc;
       this.username = username;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="path", nullable=false)
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }

    
    @Column(name="network", nullable=false)
    public String getNetwork() {
        return this.network;
    }
    
    public void setNetwork(String network) {
        this.network = network;
    }

    
    @Column(name="launch", nullable=false)
    public String getLaunch() {
        return this.launch;
    }
    
    public void setLaunch(String launch) {
        this.launch = launch;
    }

    
    @Column(name="display", nullable=false)
    public String getDisplay() {
        return this.display;
    }
    
    public void setDisplay(String display) {
        this.display = display;
    }

    
    @Column(name="platform", nullable=false)
    public String getPlatform() {
        return this.platform;
    }
    
    public void setPlatform(String platform) {
        this.platform = platform;
    }

    
    @Column(name="memory", nullable=false)
    public String getMemory() {
        return this.memory;
    }
    
    public void setMemory(String memory) {
        this.memory = memory;
    }

    
    @Column(name="maincamera", nullable=false)
    public String getMaincamera() {
        return this.maincamera;
    }
    
    public void setMaincamera(String maincamera) {
        this.maincamera = maincamera;
    }

    
    @Column(name="selfiecamera", nullable=false)
    public String getSelfiecamera() {
        return this.selfiecamera;
    }
    
    public void setSelfiecamera(String selfiecamera) {
        this.selfiecamera = selfiecamera;
    }

    
    @Column(name="sound", nullable=false)
    public String getSound() {
        return this.sound;
    }
    
    public void setSound(String sound) {
        this.sound = sound;
    }

    
    @Column(name="comms", nullable=false)
    public String getComms() {
        return this.comms;
    }
    
    public void setComms(String comms) {
        this.comms = comms;
    }

    
    @Column(name="features", nullable=false)
    public String getFeatures() {
        return this.features;
    }
    
    public void setFeatures(String features) {
        this.features = features;
    }

    
    @Column(name="battery", nullable=false)
    public String getBattery() {
        return this.battery;
    }
    
    public void setBattery(String battery) {
        this.battery = battery;
    }

    
    @Column(name="misc", nullable=false)
    public String getMisc() {
        return this.misc;
    }
    
    public void setMisc(String misc) {
        this.misc = misc;
    }

    
    @Column(name="username", nullable=false)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    public void addImage() {
        RecipeDAO dao = new RecipeDAO();
        setPath(doupload());
        dao.addImage(this);
    }
    
    public List<Projekmyspek> getAllImg(){
        RecipeDAO dao = new RecipeDAO();
        return dao.getAllImg();
    }
    
    public void saveData() {
        RecipeDAO projekmyspek = new RecipeDAO();
        projekmyspek.addSpek(this);
        this.msg = "Berhasil simpan data..";
        this.clearAll();
    }
    
    public void updateData() {
        RecipeDAO projekmyspek = new RecipeDAO();
        projekmyspek.updatespek(this);
        this.msg = "Berhasil update data..";
        this.clearAll();
    }
    
    public void deleteData() {
        RecipeDAO projekmyspek = new RecipeDAO();
        projekmyspek.destroyspek(this);
        this.msg = "Berhasil hapus data..";
        this.clearAll();
    }
    
    public List<Projekmyspek> getAllRecords() {
        this.msg = null;
        RecipeDAO projekmyspek = new RecipeDAO();
        listspek = projekmyspek.retrievespek();
        return listspek;
    }
    
    public List<Projekmyspek> getAllspekid() {
        RecipeDAO projekmyspek = new RecipeDAO();
        listspek = projekmyspek.retrievespekid();
        return listspek;
    }
    
    public void infospekid() {
        RecipeDAO projekmyspek = new RecipeDAO();
        List<Projekmyspek> ls = projekmyspek.getbyID(selectedspek);
        this.id = ls.get(0).id;
        this.path= ls.get(0).path;
        this.network = ls.get(0).network;
        this.launch = ls.get(0).launch;
        this.display = ls.get(0).display;
        this.platform = ls.get(0).platform;
        this.memory = ls.get(0).memory;
        this.maincamera= ls.get(0).maincamera;
        this.selfiecamera = ls.get(0).selfiecamera;
        this.sound = ls.get(0).sound;
        this.comms= ls.get(0).comms;
        this.features = ls.get(0).features;
        this.battery = ls.get(0).battery;
        this.misc= ls.get(0).misc;
    }

    public String doupload() {
        String path = null;
        String pathValue = null;
            try {
                InputStream in = image.getInputStream();
                File f = new File("C:\\Users\\Acer.LAPTOP-M2MD9H0R\\Documents\\NetBeansProjects\\A_Projeck_MySpek\\web\\images\\"+image.getSubmittedFileName());
                f.createNewFile();
                FileOutputStream out = new FileOutputStream(f);
                
                byte[] buffer = new byte[1024];
                int length;
                while ((length=in.read(buffer))>0) {
                    out.write(buffer, 0, length);
                }
                out.close();
                in.close();
                
                path = String.valueOf(f.getAbsolutePath());
                pathValue = "images\\"+image.getSubmittedFileName();
                System.out.println("upload success");
            } catch (Exception e) {
                System.out.println(e);
            }
            return pathValue;
}
    public void clearAll() {
        this.id = null;
        this.path = null;
        this.network = null;
        this.launch = null;
        this.display = null;
        this.platform = null;
        this.memory = null;
        this.maincamera = null;
        this.selfiecamera = null;
        this.sound = null;
        this.comms = null;
        this.features = null;
        this.battery = null;
        this.misc = null;
        this.username = null;
    }

}


